# SITE CONFIGURATION
title: Swasti Shreya # your site title
author: Swasti Shreya Mishra # You :P
description: > # Meta description of Homepage
  My blog.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "https://swastishreya.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Swasti Shreya Mishra
  links:
    - https://www.facebook.com/swastis.mishra.7
    - https://www.linkedin.com/in/swasti-shreya-mishra-189a17146/
    - https://github.com/swastishreya

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Hey! Here you can find more about me and my projects :)

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: mishra.swastishreya13@gmail.com # email for form submission

#twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:  swastishreya # replace with your_github_username or comment to remove link from footer
instagram_username: swastishreya # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname:  # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
